### ISSUE TITLE
Error in post_bulk_docs with Gzip

### ISSUE THREAD

**Issue by joebac007** [IBM/cloudant-python-sdk#554] opened 2023-09-19 13:15 UTC
**Describe the bug**
When importing a new document from a local Json document (file) via post_bulk_docs, a TypeError is thrown by Gzip compression "TypeError: a bytes-like object is required, not '_io.BufferedReader'"

**To Reproduce**
Use the code below to reproduce. Note that gzip compression is turned on by default in the client instance. Any attempt to turn it off results in a different error.
`    with open(fileName, 'rb') as f:
        response = client.post_bulk_docs(db=dbName, bulk_docs=f).get_result()
`

**Expected behavior**
The expected behavior is for the document(s) to be created and a results dictionary returned.

**Screenshots**

**Must gather (please complete the following information):**
 - SDK Version 3.16.7
 - Python Version Python 3.11
 - Name of service that you're trying to use (if applicable)
 - Name of operation that you're trying to invoke (if applicable): post_bulk_docs

**Additional context**
 No.

**Comment by joebac007** [comment] 2023-09-19 13:40
Modifying the method to:
`    with open(fileName, 'rb') as f:
        data = json.load(f)

    response = client.post_bulk_docs(db=dbName, bulk_docs=data)
`
Results in a 400 error complaining the POST is missing the "docs" parameter.  

When adding the docs parameter:
`    response = client.post_bulk_docs(db=dbName, bulk_docs=f, docs=data)
`
A different error is thrown: "TypeError: Session.request() got an unexpected keyword argument 'docs'"

**Comment by joebac007** [comment] 2023-09-19 13:53
The compress method from gzip.py is where the error is being thrown from.  It doesn't appear it's expecting an IO Stream.
<img width="1039" alt="image" src="https://github.com/IBM/cloudant-python-sdk/assets/25378030/bc65fd29-522f-4f3f-85e1-a9c091384c87">

**Comment by ricellis** [comment] 2023-09-19 13:55
I was able to reproduce, we'll look into the type problem.

The workaround to [disable request body compression](https://github.com/IBM/cloudant-python-sdk/blob/main/KNOWN_ISSUES.md#disabling-request-body-compression) works for me with:
```python
service = CloudantV1.new_instance()
service.set_enable_gzip_compression(False)

with open(fileName, 'rb') as f:
  response = service.post_bulk_docs(
    db=dbName,
    bulk_docs=f
  ).get_result()
```

your binary file will need to have the form of the request body, namely an object contianing an array of `docs`:
```json
{
  "docs": [
      {
      "_id": "abc"
      },
      {
      "_id": "def",
      }
  ]
}
```

**Comment by joebac007** [comment] 2023-09-19 13:58
Thanks! It's working for me now with turning off compression and adding the "docs" section.

**Comment by ricellis** [comment] 2023-09-20 10:31
It is also possible to get this to work correctly with compression enabled by passing the bytes rather than the file object i.e.
```python
  response = service.post_bulk_docs(
    db=dbName,
    bulk_docs=f.read()
  ).get_result()
```

**Comment by joebac007** [comment] 2023-09-20 19:27
Thanks! Using the read method works perfectly.

**Comment by eiri** [comment] 2023-10-30 16:34
This should be fixed with updated core's version that was included in https://github.com/IBM/cloudant-python-sdk/releases/tag/v0.7.0

**Closed by eiri** 2023-10-30 16:34 UTC
